name: adopt
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.17
  firebase_storage: ^10.2.17
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  equatable: ^2.0.3
  image_picker: ^0.8.5+3
  file_picker: ^4.6.1
  flutter_bloc: ^8.0.1 
  core:
    path: ../core
  url_launcher: ^6.1.3
  font_awesome_flutter: ^10.1.0
  notification:
    path: ../notification
  flutter_svg: ^1.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
