name: pethouse
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  core:
    path: core
  user:
    path: user
  task:
    path: task
  store:
    path: store
  petrivia:
    path: petrivia
  pet:
    path: pet
  pet_map:
    path: pet_map
  plan:
    path: plan
  notification:
    path: notification
  adopt:
    path: adopt
  google_fonts: ^2.3.3
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  percent_indicator: ^4.2.2
  carousel_slider: ^4.1.1
  table_calendar: ^3.0.5
  google_maps_flutter: ^2.1.8
  flutter_speed_dial: ^6.0.0
  iconify_flutter: ^0.0.4
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  date_picker_timeline: ^1.2.3
  charts_flutter: ^0.12.0
  sqflite: ^2.0.2+1
  get_it: ^7.1.3
  flutter_bloc: ^8.0.1
  url_launcher: ^6.1.3
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17
  file_picker: ^4.6.1
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^9.6.0
  rxdart: ^0.27.4
  flutter_spinkit: ^5.1.0
  android_alarm_manager_plus: ^2.0.5
  geolocator: ^8.2.1
  http: ^0.13.4
  html: ^0.15.0
  flutter_map: ^1.0.0
  latlong2: ^0.8.1
  cached_network_image: ^3.2.1
  awesome_dialog: ^2.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/vectors/
