name: store
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.1
  http: ^0.13.4
  html: ^0.15.0
  url_launcher: ^6.1.3
  core:
    path: ../core
  flutter:
    sdk: flutter
  awesome_dialog: ^2.2.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
