name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.3
  flutter_svg: ^1.0.3
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^10.1.0
  flutter_spinkit: ^5.1.0
  flutter_local_notifications: ^9.6.0
  rxdart: ^0.27.4
  timezone: ^0.8.0
  intl: ^0.17.0
  android_alarm_manager_plus: ^2.0.5
  shared_preferences: ^2.0.15
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

