name: pet
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  core:
    path: ../core
  intl: ^0.17.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1 
  firebase_storage: ^10.2.17
  image_picker: ^0.8.5+3
  file_picker: ^4.6.1
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.0
  url_launcher: ^6.1.3
  charts_flutter: ^0.12.0
  task:
    path: ../task
  plan:
    path: ../plan
  uuid: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
